language: go

go:
  - 1.5.1

env:
  matrix:
    - ES_VERSION=1.7.3

before_script:
  - mkdir ${HOME}/elasticsearch
  - wget http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch >& /dev/null &
  - sleep 15
  - curl -XGET http://localhost:9200/

sudo: false

script:
  - GIMME_GO_VERSION=1.5 gimme --list
  - go build -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get gopkg.in/olivere/elastic.v2
  - go test -v -covermode=count -coverprofile=coverage.out github.com/wookay/elasticcat

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 7cRm8ihT7GFiA5sxKaTGi2tJ0drtnpMT9

notifications:
  email: false
